# Generated by Django 4.0 on 2023-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('pwd', models.IntegerField()),
                ('role', models.CharField(choices=[('CR', 'Customer'), ('SR', 'Seller')], default='CR', max_length=2)),
                ('user_uuid', models.CharField(default='2010447e-c9c2-11ed-81a0-0abc79988a85', max_length=1024)),
            ],
        ),
    ]
