# Generated by Django 4.0 on 2023-03-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerseller',
            name='pwd',
            field=models.IntegerField(max_length=256),
        ),
    ]
