# Generated by Django 4.0 on 2023-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerseller',
            name='user_uuid',
            field=models.CharField(default='2364620e-c9c2-11ed-8a50-0abc79988a85', max_length=1024),
        ),
    ]
