# Generated by Django 4.0 on 2023-03-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0002_alter_customerseller_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerseller',
            name='user_uuid',
            field=models.CharField(max_length=1024),
        ),
    ]
