# Generated by Django 4.0 on 2023-03-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0002_alter_customerseller_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerseller',
            name='user_uuid',
            field=models.CharField(default='34c28a32-c9b1-11ed-b6b9-0abc79988a85', max_length=1024),
        ),
        migrations.AlterField(
            model_name='customerseller',
            name='pwd',
            field=models.IntegerField(),
        ),
    ]
