# Generated by Django 4.0 on 2023-03-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='sold',
            new_name='bought',
        ),
    ]
